package testutilities.context;

public enum Context {
    MOBANK_REGISTRATION_TYPE,
    INTERNET_BANKING,
    CIF_DEBIT_CARD,
    CIF_PAN,
    CIF_PASSPORT,
    IS_APP_INSTALLED,
    IS_CONFIRMATION_ALERT_MESSAGE_DISPLAYED,
    SEND_MONEY_TRANSACTION_REFERENCE_NUMBER,
    SELECTED_ID_TYPE,
    PAY_TO_CONTACT,
    CURRENT_SCREEN_NAME,
    ENTERED_SEND_MONEY_DETAILS,
    ENTERED_SEND_MONEY_FREQUENCY,
    ENTERED_SEND_MONEY_NO_OF_TIMES,
    RECHARGE_DETAILS,
    BANK_NAME,
    PAY_LATER,
    PAY_TO_CONTACT_DETAILS,
    SELECTED_BANK_NAME,
    PAYEE_DETAILS,
    PAY_TO_CONTACT_REFERENCE_NUMBER,
    RECHARGE_DETAILS_TRANSACTION_REFERENCE_NUMBER,
    PAY_TO_CONTACT_DATE,
    PREVIOUS_SCREEN_NAME;



}
